version: '3'
services:  
  db:
    image: cockroachdb/cockroach:v23.1.11
    ports:
      - "26257:26257"
      - "8080:8080"
    environment:
      COCKROACH_DATABASE: moneymate_db_local
    healthcheck:
      test: curl -f http://localhost:8080/health?ready=1
      interval: 1s
      timeout: 3s
      retries: 5
    command: start-single-node --insecure
    
  dbmigration:
    image: flyway/flyway:10
    container_name: flyway
    environment:
      FLYWAY_URL: ${COCKROACH_DB_URL:-jdbc:postgresql://host.docker.internal:26257/moneymate_db_local}
      FLYWAY_USER: ${COCKROACH_DB_USER:-root}
      FLYWAY_PASSWORD: ${COCKROACH_DB_PASSWORD:-}
    command: migrate -connectRetries=60
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
    extra_hosts: 
      - "host.docker.internal:host-gateway"