services:
  localstack:
    image: localstack/localstack:1.3.0
    environment:
      SERVICES: ssm
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
    volumes:
      - type: bind
        source: ./.docker/localstack/healthcheck.sh
        target: /app/healthcheck.sh
    ports:
      - "4566:4566"
    healthcheck:
      test: [ "CMD", "/app/healthcheck.sh" ]
      interval: 3s
      retries: 5
      timeout: 10s
  
  google_api_mock:
    build:
      context: ./.docker/google_api_mock
    environment:
      FLASK_DEBUG: 1
    ports:
      - "6001:5000"

  terraform_apply:
    image: hashicorp/terraform:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_REGION=${AWS_REGION:-}
      - TF_WORKSPACE=${ENVIRONMENT}
      - TF_VAR_CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - TF_VAR_CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - TF_VAR_MONEYMATE_API_LAMBDA_IMAGE_TAG=${IMAGE_TAG}
      - TF_VAR_DIGITAL_OCEAN_TOKEN=${DIGITAL_OCEAN_TOKEN}
    volumes:
      - ./infra:/code
    working_dir: /code
    entrypoint: ["/bin/sh", "-c", "terraform init && terraform apply -auto-approve"]
    