name: "MoneyMate_Core_Infra"

on:
  push:
    branches:
      - master
    paths: 
      - 'infra/**'
      - 'scritps/**'
      - '.github/workflows/core_infra.yml'

jobs:
  provision_infra_test:
    name: Provision Infra for Test
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: test
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      COCKROACH_API_KEY: ${{secrets.COCKROACH_DB_API_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run terraform apply
        run: ./batect terraform_apply

  provision_infra_prod:
    name: Provision Infra for Prod
    needs:
      - provision_infra_test
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      COCKROACH_API_KEY: ${{secrets.COCKROACH_DB_API_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run terraform apply
        run: ./batect terraform_apply